stages:
  - build
  - test
  - package

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests=false"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:24-dind

build_job:
  stage: build
  image: maven:3.9.4-eclipse-temurin-21-alpine
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/

test_job:
  stage: test
  image: maven:3.9.4-eclipse-temurin-21-alpine
  script:
    - mvn test

package_job:
  stage: package
  image: maven:3.9.4-eclipse-temurin-21-alpine
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
