name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.4-eclipse-temurin-21-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Maven
        run: echo "Using Maven in container"

      - name: Compile
        run: mvn clean compile

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-target
          path: target/

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.4-eclipse-temurin-21-alpine
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-target
          path: target/

      - name: Run tests
        run: mvn test

  package:
    name: Package
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.4-eclipse-temurin-21-alpine
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and package
        run: mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: target/*.jar
